### ISSUE TITLE
MQTT broken for sensors that send multiple reading data in a single topic 

### ISSUE THREAD

**Issue by bluemodena** [avollkopf/craftbeerpi4#23]
I think I have found a bug in the MQTT sensor code. It assumes that each mqtt topic will be unique per sensor.   
While normally that is true, when you have Tilt Hydrometer that sends both temp and gravity readings in the same json data,
it doesn't work.... only the first value gets processed by cbpi.

topic:home/brewery/tilts/blue
payload:{"tilt": "blue", 
         "time": "2021-12-26 14:28:21.152014", 
         "temperature": "65",
         "gravity": 1.018, 
         "measurementID": "8d0099bd-dbc3-4639-b30d-fee5070884bf", 
         "msg_uuid": "af58321e-8601-4776-bdcd-14704b8525b2", 
         "time_send": "2021-12-26 14:28:21.154034"}

when a new message arrives, the extension/mqtt_sensor/__init__.py code handles the on_message call.
it finds the temperature key in the json and self.push_update(self.value) is called for just temperature. The message does 
not get processed again for the gravity sensor as it only gets called once per topic subscription so the gravity 
reading is never read by cbpi.

I think what is needed is for the code to loop over the other sensors looking for mqtt sensors that have the same 
topic and process the json data for the other key:value pairs. In my case, it'll only be temp and gravity, but it could
be many more than that.

what I ended up doing is creating a unique topic per sensor and it's working. 

topic:home/brewery/tilts/blue_temp
	{"tilt": "blue", 
	"time": "2021-12-26 14:33:22.908561", 
	"temperature": "65", 
	"measurementID": "4315f2f5-649e-4998-88ce-0cafc4a3bb2c", 
	"msg_uuid": "73c11fab-0559-45c5-b900-28fe70aa61dd", 
	"time_send": "2021-12-26 14:33:22.910101"}

topic:home/brewery/tilts/blue_gravity
	{"tilt": "blue", 
	"time": "2021-12-26 14:33:22.908857", 
	"gravity": 1.018, 
	"measurementID": "d72a3d0d-e33c-4faa-ab38-2b385e6bd4f0", 
	"msg_uuid": "50527796-37f7-4136-b2d0-8f2875a6ba16", 
	"time_send": "2021-12-26 14:33:22.934892"}

  
I know enough to be dangerous, but not enough to 
know what needs to be changed in cbpi (or simply have a dedicated Tilt plugin sensor that will handle this automatically.

**Comment by avollkopf** [comment]
Well, it's not broken as it is a 1:1 copy from V3 mqtt sensor and works as it is intended to work. 

I think, that this should not be handled by the simple mqtt sensor. This should be done by a plugin, like it is available for the ispindle. The ispindle has basically the same situation. Several values will be reported by one 'Sensor'. The plugin receives a set of values and stores them in a cache.

Now the user can define multiple ispindel sensors and define for each sensor the value that should be reported/displayed.

The problem with the tilt is, that I don't own one. Hence, I cannot migrate the old plugin or create a new one since it is bluetooth based which needs to be integrated into the plugin.

**Comment by avollkopf** [comment]
titl should work natively now with cbpi4-BLEHydrom plugin. Requested function would require creation plugin

**Comment by bluemodena** [comment]
thanks @avollkopf, I will give the new plugin a shot over the weekend.  Ultimately, for my needs I want it in MQTT format with my other MQTT enabled devices, but having cbpi4 being able to read the Tilt directly will solve the most immediate concern.  Thanks again.
