### ISSUE TITLE
plugins

### ISSUE THREAD

**Issue by dimontau** [avollkopf/craftbeerpi4#61]
Hello. Can I add a plugin for physical buttons on gpio?
Or how can I migrate the GPIObutton plugin to CraftBeerPi 3.0?
will it work if i add setup.py?

**Comment by prash3r** [comment]
Hey,

cbpi3 and cbpi4 plugins are not compatible at all. If you are familiar with python then this [documentation page](https://openbrewing.gitbook.io/craftbeerpi4_support/readme/development/plugin_development) and the

`cbpi create`

command should get you started in the right direction.

**Comment by dimontau** [comment]
I am not familiar with python at all. Can you help me write a plugin?

**Comment by avollkopf** [comment]
I don't know the plugin and if it is for cbpi3, somebody would need to port it to cbpi4. It won't be working out of the box. Not an issue with cbpi4 -> needs to be opened on the plugin repo.

**Comment by prash3r** [comment]
i tried to migrate the existing cbpi3 GPIOButton plugin [https://github.com/jhhbe/cbpi](https://github.com/jhhbe/cbpi) but my tests regarding api calls are not successfull and at the moment i cant test the GPIO part of it.

Since i wont be able to test this on a Pi for some time i published my current state and if you want to try it you can. Then open any issues on my repo (https://github.com/prash3r/cbpi4-GPIOButton)[https://github.com/prash3r/cbpi4-GPIOButton].

it may just doesnt work on my end because of docker restrictions or it may requires some sort of cookie for the request.

This issue can stay closed.
